PLANT_PROFILES = {
    "monstera": {
        "label": "Monstera (Swiss Cheese Plant)",
        "watering": "Every 1-2 weeks; let top 2 inches dry completely. Reduce to every 3 weeks in winter. Sensitive to fluoride — use filtered or rainwater. Ensure drainage holes at all times.",
        "sunlight": "Bright indirect light, 1-2 m from a south/east window. Direct sun bleaches leaves. Low light stops leaf fenestration (splits).",
        "humidity": "Prefers 60-80%. Mist in mornings with filtered water. Brown crispy edges = air too dry.",
        "temperature": "18-27°C. Below 10°C causes black mushy cell damage. Keep away from AC vents.",
        "fertiliser": "Monthly in spring/summer with balanced NPK 20-20-20. Stop in autumn/winter.",
        "diseases": "Root rot (black mushy roots — trim, treat with 3% H2O2, repot). Bacterial leaf blight (water-soaked brown spots with yellow halo). Fungal spots (high humidity + overwatering).",
        "pests": "Spider mites (fine webbing on leaf undersides — neem oil). Scale insects (brown bumps on stems — isopropyl alcohol).",
        "emergency": "Sudden drooping + wet soil = root rot emergency. All-over yellowing = severe overwatering. Black patches = cold damage or bacterial infection.",
        "watering_frequency_days": 10,
        "humidity_ideal": (60, 80),
        "temp_ideal": (18, 27),
    },
    "snake_plant": {
        "label": "Snake Plant (Sansevieria)",
        "watering": "Every 2-6 weeks; once a month or less in winter. Never overwater — they rot instantly. Firm leaves = hydrated; wrinkled/bendy = water now.",
        "sunlight": "Adapts from low light to bright indirect. Bright indirect = fastest growth and best variegation. Avoid prolonged direct midday sun.",
        "humidity": "Low humidity tolerant (30-50% fine). High humidity >70% + overwatering = root rot. No misting needed.",
        "temperature": "18-27°C. Below 10°C causes mushy cell damage. Avoid cold draughts near windows.",
        "fertiliser": "2-3 times per growing season only at half-strength balanced fertiliser. Over-feeding causes white salt crust.",
        "diseases": "Root rot (mushy discoloured base — remove, cut rot, dust with cinnamon, repot in DRY mix). Red leaf spot fungus. Mealybugs (white fluffy deposits at leaf base).",
        "pests": "Mealybugs (white fluffy deposits). Spider mites (rare).",
        "emergency": "Mushy discoloured base = root rot emergency. Sudden leaf collapse = cold damage or severe overwatering.",
        "watering_frequency_days": 21,
        "humidity_ideal": (30, 50),
        "temp_ideal": (18, 27),
    },
    "pothos": {
        "label": "Pothos (Devil's Ivy)",
        "watering": "Every 1-2 weeks; top 2 inches must dry first. Wilting + dry soil = thirsty. Wilting + wet soil = root rot. Yellow leaves = overwatering.",
        "sunlight": "Adapts to low light but fastest growth in bright indirect. Variegated varieties need more light to maintain patterns.",
        "humidity": "50-70% ideal. Brown tips = too dry.",
        "temperature": "18-29°C. Avoid below 10°C.",
        "fertiliser": "Monthly in spring/summer with balanced liquid fertiliser.",
        "diseases": "Root rot (black mushy stems at base + yellowing). Bacterial leaf spot (water-soaked brown patches with yellow halos).",
        "pests": "Mealybugs, spider mites, scale insects.",
        "emergency": "Black stem base = root rot emergency. Sudden collapse of vines = severe root rot or cold shock.",
        "watering_frequency_days": 10,
        "humidity_ideal": (50, 70),
        "temp_ideal": (18, 29),
    },
    "aloe_vera": {
        "label": "Aloe Vera",
        "watering": "Every 2-3 weeks in summer, every 4-6 weeks in winter. Soil MUST dry completely. Water at base only — never the crown. Yellow/mushy base = overwatered.",
        "sunlight": "6+ hours bright direct or indirect light. South/east windowsill ideal. Reddish blushing = sun stress, move to partial shade.",
        "humidity": "Prefers low humidity (30-40%). Never mist. High humidity + overwatering = crown/root rot.",
        "temperature": "15-29°C. Below 4°C = frost damage.",
        "fertiliser": "Once or twice a year only (early spring and mid-summer). Diluted, phosphorus-heavy.",
        "diseases": "Crown rot (soft brown mushy base — cut all rot, air dry 2-3 days, repot in completely DRY cactus mix). Rust spots = overhead watering fungal. Aloe mites = lumpy abnormal growth.",
        "pests": "Aloe mites (lumpy growths — no cure, remove). Scale insects.",
        "emergency": "Soft mushy base = root/crown rot emergency. Drooping + no watering issues = frost damage or sun stress.",
        "watering_frequency_days": 18,
        "humidity_ideal": (30, 40),
        "temp_ideal": (15, 29),
    },
    "peace_lily": {
        "label": "Peace Lily (Spathiphyllum)",
        "watering": "Weekly in spring/summer, every 10 days in autumn/winter. Consistently moist but never waterlogged. Use filtered or distilled water (sensitive to fluoride).",
        "sunlight": "Low to medium indirect light — one of the best for dim rooms. Direct sun scorches leaves.",
        "humidity": "Loves humidity above 50%. Brown crispy tips = dry air. Daily misting in mornings.",
        "temperature": "18-30°C. Below 15°C causes black water-soaked patches.",
        "fertiliser": "Monthly spring/summer with phosphorus-rich fertiliser (5-10-5) to encourage blooming.",
        "diseases": "Root rot (drooping despite correct watering). Spider mites in hot dry air (fine webbing on leaf undersides).",
        "pests": "Spider mites, aphids.",
        "emergency": "Drooping despite correct watering = root rot. Sudden collapse = cold shock.",
        "watering_frequency_days": 7,
        "humidity_ideal": (50, 70),
        "temp_ideal": (18, 30),
    },
    "zz_plant": {
        "label": "ZZ Plant (Zamioculcas zamiifolia)",
        "watering": "Every 2-3 weeks in summer, every 3-4 weeks in winter. NEVER water unless soil is completely dry. Yellow leaves = classic overwatering sign.",
        "sunlight": "Tolerates very low light better than almost any other plant. Direct sun causes yellow bleached patches.",
        "humidity": "Low humidity tolerant (30-50% fine). Very dry air (<20%) may cause brown tips.",
        "temperature": "18-28°C. Below 8°C damages rhizomes.",
        "fertiliser": "2-3 times per growing season, half-strength. Single slow-release pellet in spring is ideal.",
        "diseases": "Rhizome rot (plant collapses, stems black at base, musty smell). Scale insects and mealybugs.",
        "pests": "Scale insects, mealybugs.",
        "emergency": "Collapsing stems + musty smell = rhizome rot emergency. NOTE: toxic to cats, dogs, and humans.",
        "watering_frequency_days": 21,
        "humidity_ideal": (30, 50),
        "temp_ideal": (18, 28),
    },
    "fiddle_leaf_fig": {
        "label": "Fiddle Leaf Fig (Ficus lyrata)",
        "watering": "Weekly in spring/summer, thoroughly until drainage. Consistency is critical — pick a watering day and stick to it. Hates unpredictability.",
        "sunlight": "Bright indirect, 6+ hours daily. Once positioned, DO NOT move it — notorious for dropping leaves when relocated.",
        "humidity": "30-65%. Brown crispy edges = dry air — use humidifier. Avoid heating vents in winter.",
        "temperature": "16-24°C. Below 13°C causes immediate leaf drop.",
        "fertiliser": "Monthly spring/summer with nitrogen-rich fertiliser (3-1-2 NPK).",
        "diseases": "Root rot (#1 killer — large brown spots starting at leaf base). Bacterial infection (dark brown spots with yellow halo — spreads rapidly).",
        "pests": "Spider mites and scale insects on stressed plants.",
        "emergency": "Multiple leaves dropping suddenly = cold shock or relocation stress. Dark spreading spots from base = root rot emergency.",
        "watering_frequency_days": 7,
        "humidity_ideal": (30, 65),
        "temp_ideal": (16, 24),
    },
    "spider_plant": {
        "label": "Spider Plant (Chlorophytum comosum)",
        "watering": "Every 1-2 weeks; allow top 50% of soil to dry. Brown tips from fluoride — use filtered/rainwater.",
        "sunlight": "Bright to medium indirect light. Produces most babies (spiderettes) in bright conditions.",
        "humidity": "40-60% preferred. Brown tips in very dry air.",
        "temperature": "13-27°C — most temperature-tolerant houseplant. Below 7°C causes damage.",
        "fertiliser": "Monthly spring/summer with balanced liquid fertiliser.",
        "diseases": "Root rot (from overwatering). Spider mites (fine webbing — neem oil).",
        "pests": "Spider mites, aphids, mealybugs.",
        "emergency": "All leaves browning rapidly = root rot or cold damage.",
        "watering_frequency_days": 10,
        "humidity_ideal": (40, 60),
        "temp_ideal": (13, 27),
    },
    "succulent": {
        "label": "Succulent (General)",
        "watering": "Every 7-14 days in summer, every 3-4 weeks in winter. Soil MUST dry completely. Overwatering is the #1 killer.",
        "sunlight": "6+ hours bright direct or indirect light. Stretched/etiolated growth = insufficient light.",
        "humidity": "Low humidity (20-40%) preferred. Never mist.",
        "temperature": "Most prefer 16-27°C. Many are frost-sensitive.",
        "fertiliser": "Once in spring and once in summer with succulent-specific diluted fertiliser.",
        "diseases": "Root rot (overwatering). Mealybugs. Scale insects.",
        "pests": "Mealybugs (#1 pest), scale insects, fungus gnats.",
        "emergency": "Mushy translucent leaves = severe overwatering/rot. Wrinkled leaves + dry soil = underwatering.",
        "watering_frequency_days": 14,
        "humidity_ideal": (20, 40),
        "temp_ideal": (16, 27),
    },
    "default": {
        "label": "General Houseplant",
        "watering": "Water when the top 1-2 inches of soil feel dry. Overwatering is the #1 killer of houseplants. Always check soil before watering.",
        "sunlight": "Most houseplants prefer bright indirect light near a window, away from harsh direct afternoon sun.",
        "humidity": "Most houseplants thrive at 50-70%. Group plants together or use a pebble tray.",
        "temperature": "Most houseplants prefer 18-28°C. Keep away from AC vents, heaters, and cold draughts.",
        "fertiliser": "Feed every 2-4 weeks in spring and summer with balanced NPK 10-10-10.",
        "diseases": "Root rot (overwatering). Fungal leaf spots (high humidity + poor airflow). Bacterial infections.",
        "pests": "Spider mites, mealybugs, scale insects, fungus gnats. Check leaf undersides regularly.",
        "emergency": "Sudden wilting despite correct watering, rapid yellowing, or black mushy stems all require immediate action.",
        "watering_frequency_days": 10,
        "humidity_ideal": (50, 70),
        "temp_ideal": (18, 28),
    }
}

PLANT_KEYWORD_MAP = {
    "monstera": "monstera", "swiss cheese": "monstera",
    "snake plant": "snake_plant", "sansevieria": "snake_plant", "dracaena trifasciata": "snake_plant",
    "peace lily": "peace_lily", "spathiphyllum": "peace_lily",
    "pothos": "pothos", "devil's ivy": "pothos", "epipremnum": "pothos",
    "spider plant": "spider_plant", "chlorophytum": "spider_plant",
    "aloe vera": "aloe_vera", "aloe": "aloe_vera",
    "zz plant": "zz_plant", "zamioculcas": "zz_plant", "zanzibar": "zz_plant",
    "fiddle leaf": "fiddle_leaf_fig", "ficus lyrata": "fiddle_leaf_fig", "ficus": "fiddle_leaf_fig",
    "succulent": "succulent", "cactus": "succulent", "echeveria": "succulent",
}

def detect_plant(text: str) -> dict:
    text_lower = text.lower()
    for keyword, key in PLANT_KEYWORD_MAP.items():
        if keyword in text_lower:
            return PLANT_PROFILES.get(key, PLANT_PROFILES["default"])
    return PLANT_PROFILES["default"]

def get_all_plants() -> dict:
    return {k: {"label": v["label"]} for k, v in PLANT_PROFILES.items() if k != "default"}
